# Generated by Django 6.0.1 on 2026-02-09 18:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalAquisicaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Canal de Aquisição',
                'verbose_name_plural': 'Canais de Aquisição',
                'db_table': 'canal_aquisicao_cliente',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoProximo12Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Objetivo (12 meses)',
                'verbose_name_plural': 'Objetivos (12 meses)',
                'db_table': 'objetivo_proximo_12_meses',
            },
        ),
        migrations.CreateModel(
            name='RestricaoCritica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Restrição Crítica',
                'verbose_name_plural': 'Restrições Críticas',
                'db_table': 'restricao_critica',
            },
        ),
        migrations.CreateModel(
            name='SistemaUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Sistema Utilizado',
                'verbose_name_plural': 'Sistemas Utilizados',
                'db_table': 'sistema_utilizado',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=200, verbose_name='Nome da empresa')),
                ('setor_atuacao', models.CharField(choices=[('AGRO', 'Agronegócio / Pecuária / Rural'), ('ALIMENTOS', 'Alimentos / Bebidas'), ('PET', 'Animais de Estimação / Mundo Pet'), ('ARQUITETURA', 'Arquitetura / Design de Interiores'), ('ARTISTICO', 'Artístico / Musical / Produtora'), ('AUTOMOBILISTICO', 'Automobilístico'), ('COMBUSTIVEIS', 'Combustíveis / Energia'), ('CONSTRUCAO', 'Construção Civil / Incorporadora'), ('CONTABILIDADE', 'Contabilidade'), ('BELEZA', 'Cosméticos / Beleza / Estética'), ('DIVERSOS', 'Diversos'), ('ECOMMERCE', 'E-commerce / Marketplace'), ('EDUCACAO', 'Educação'), ('ENERGIA_SOLAR', 'Energia Solar'), ('ENGENHARIA', 'Engenharia / Infraestrutura'), ('ELETRO', 'Equipamentos Eletrodomésticos / Eletrônicos'), ('ESPORTE', 'Esporte / Lazer / Jogos / Bem-estar'), ('EVENTOS', 'Eventos'), ('FARMACEUTICA', 'Farmacêutica / Drogarias'), ('GESTAO', 'Gestão / Administração / Consultorias'), ('IMOBILIARIA', 'Imobiliária'), ('IMPORT_EXPORT', 'Importação e Exportação'), ('INVESTIMENTO', 'Investimento / Financeiro'), ('JURIDICO', 'Jurídico'), ('LOGISTICA', 'Logística / Distribuidora / Transporte de carga'), ('MARKETING', 'Marketing'), ('MEDICINA_DIAG', 'Medicina Diagnóstica / Laboratórios'), ('METALURGIA', 'Metalúrgica / Mineração'), ('MAQUINAS', 'Máquinas e Equipamentos'), ('MEDICOS', 'Médicos / Dentistas / Clínicas / Institutos Médicos'), ('MOVEIS', 'Móveis e Decoração'), ('PAPEL', 'Papel / Celulose / Plástico'), ('HOSPITALAR', 'Produtos e equipamentos para hospitais e clínicas'), ('PUBLICIDADE', 'Publicidade / Propaganda'), ('PUBLICO', 'Público / Governamental'), ('QUIMICA', 'Química'), ('RECICLAGEM', 'Reciclagem e Sustentabilidade'), ('ATACADO_VAREJO', 'Redes de Atacado ou Varejo'), ('TELECOM', 'Redes e Telecomunicações'), ('RH', 'RH / Recrutamento e Seleção'), ('TI', 'SaaS / Plataformas / Softwarehouse / TI'), ('SEGUROS', 'Seguros'), ('SEGURANCA_LIMPEZA', 'Serviços de Segurança / Limpeza'), ('TRANSPORTE', 'Transporte e Mobilidade'), ('TURISMO', 'Turismo / Hotelaria'), ('MODA', 'Vestuário & Moda'), ('COMUNICACAO', 'Veículos de comunicação'), ('OUTRO', 'Outro (descreva)')], max_length=50, verbose_name='Setor de atuação')),
                ('cargo', models.CharField(blank=True, choices=[('SOCIO', 'Sócio ou Fundador'), ('PRESIDENTE', 'Presidente ou CEO'), ('VP', 'Vice-presidente ou C-Level'), ('DIRETOR', 'Diretor'), ('GERENTE', 'Gerente'), ('COORDENADOR', 'Coordenador'), ('SUPERVISOR', 'Supervisor'), ('ANALISTA', 'Analista'), ('OUTRO', 'Outro (descreva)')], max_length=50, verbose_name='Cargo')),
                ('segmento_especifico', models.CharField(help_text='Lista dinâmica com base no setor selecionado.', max_length=160, verbose_name='Segmento específico')),
                ('fase_negocio', models.CharField(blank=True, choices=[('IDEACAO', 'Ideação (pré-operação)'), ('OPERACAO_INICIAL', 'Operação inicial'), ('CRESCIMENTO', 'Em crescimento'), ('ESTAVEL', 'Estável'), ('DIFICULDADE', 'Em dificuldade')], max_length=24, verbose_name='Fase do negócio')),
                ('faixa_ano_fundacao', models.CharField(blank=True, choices=[('ANTES_2010', 'Antes de 2010'), ('2010_2015', '2010–2015'), ('2016_2020', '2016–2020'), ('2021_2025', '2021–2025'), ('2026_MAIS', '2026 ou posterior')], max_length=16, verbose_name='Ano de fundação (faixa)')),
                ('faixa_funcionarios', models.CharField(blank=True, choices=[('UM', '1 (apenas o(a) fundador(a))'), ('2_9', '2–9'), ('10_25', '10–25'), ('26_100', '26–100'), ('100_MAIS', '100+')], max_length=16, verbose_name='Número de funcionários')),
                ('decisao_estrategica', models.CharField(blank=True, choices=[('DONO', 'Dono(a)'), ('SOCIOS', 'Sócios'), ('GESTORES', 'Gestor(es)'), ('TIME_EXECUTIVO', 'Time executivo')], max_length=20, verbose_name='Quem toma as decisões estratégicas?')),
                ('responsavel_tecnologia_processos', models.CharField(blank=True, choices=[('NINGUEM', 'Não há responsável definido'), ('DONO', 'Dono(a)'), ('ADMINISTRATIVO', 'Pessoa administrativa'), ('TI_INTERNO', 'TI interno'), ('FORNECEDOR', 'Fornecedor/parceiro externo')], max_length=24, verbose_name='Responsável por tecnologia e processos')),
                ('regime_tributario', models.CharField(blank=True, choices=[('MEI', 'MEI'), ('SIMPLES', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real')], max_length=20, verbose_name='Regime tributário')),
                ('faturamento_anual_aproximado', models.CharField(blank=True, choices=[('NAO_FATURAMOS', 'Ainda não faturamos'), ('ATE_100K', 'Até R$ 100 mil'), ('100K_1M', 'R$ 100 mil – R$ 1 milhão'), ('1M_5M', 'R$ 1 milhão – R$ 5 milhões'), ('5M_25M', 'R$ 5 milhões – R$ 25 milhões'), ('25M_100M', 'R$ 25 milhões – R$ 100 milhões'), ('ACIMA_100M', 'Acima de R$ 100 milhões')], max_length=20, verbose_name='Faturamento anual aproximado')),
                ('orcamento_anual_ti', models.CharField(blank=True, choices=[('NAO_DEFINIDO', 'Não possuo / não definido'), ('ATE_10K', 'Até R$ 10 mil'), ('10K_50K', 'R$ 10 mil – R$ 50 mil'), ('50K_100K', 'R$ 50 mil – R$ 100 mil'), ('100K_250K', 'R$ 100 mil – R$ 250 mil'), ('250K_1M', 'R$ 250 mil – R$ 1 milhão'), ('ACIMA_1M', 'Acima de R$ 1 milhão')], max_length=20, verbose_name='Orçamento anual disponível para TI / tecnologia')),
                ('modelo_negocio', models.CharField(blank=True, choices=[('B2B', 'B2B (vende para empresas)'), ('B2C', 'B2C (vende para consumidor final)'), ('B2B2C', 'B2B2C'), ('B2G', 'B2G'), ('D2C', 'D2C'), ('MARKETPLACE', 'Marketplace'), ('HIBRIDO', 'Híbrido')], max_length=16, verbose_name='Modelo de negócio')),
                ('tipo_receita_predominante', models.CharField(blank=True, choices=[('VENDA_UNICA', 'Venda única (transacional)'), ('RECORRENCIA', 'Recorrência / assinatura'), ('SERVICOS', 'Serviços por hora ou projeto'), ('COMISSOES', 'Comissões'), ('MIX', 'Mix de modelos')], max_length=20, verbose_name='Tipo de receita predominante')),
                ('ticket_medio_venda', models.CharField(blank=True, choices=[('ATE_100', 'Até R$ 100'), ('101_500', 'R$ 101 – R$ 500'), ('501_2000', 'R$ 501 – R$ 2.000'), ('2000_10K', 'R$ 2.000 – R$ 10.000'), ('ACIMA_10K', 'Acima de R$ 10.000')], max_length=16, verbose_name='Ticket médio de venda')),
                ('principal_canal_vendas', models.CharField(blank=True, choices=[('LOJA_FISICA', 'Loja física'), ('ECOMMERCE', 'E-commerce / site próprio'), ('WHATSAPP', 'WhatsApp'), ('REDES_SOCIAIS', 'Redes sociais'), ('VENDEDORES_EXTERNOS', 'Vendedores externos / representantes'), ('MARKETPLACES', 'Marketplaces')], max_length=24, verbose_name='Principal canal de vendas')),
                ('estrutura_operacional', models.CharField(blank=True, choices=[('PRESENCIAL', '100% presencial'), ('ONLINE', '100% online'), ('HIBRIDA', 'Híbrida'), ('MULTILOJA', 'Multiloja / múltiplas unidades')], max_length=16, verbose_name='Estrutura operacional')),
                ('quantidade_unidades', models.CharField(blank=True, choices=[('UMA', '1'), ('2_5', '2–5'), ('6_20', '6–20'), ('20_MAIS', '20+')], max_length=16, verbose_name='Quantidade de unidades / filiais')),
                ('abrangencia_geografica', models.CharField(blank=True, choices=[('LOCAL', 'Local / bairro'), ('CIDADE', 'Cidade'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], max_length=16, verbose_name='Abrangência geográfica')),
                ('sazonalidade_negocio', models.CharField(blank=True, choices=[('BAIXA', 'Baixa'), ('MODERADA', 'Moderada'), ('ALTA', 'Alta')], max_length=12, verbose_name='Sazonalidade do negócio')),
                ('meses_pico', models.CharField(blank=True, help_text='Ex.: mar, abr, nov. Preencher apenas se sazonalidade for moderada/alta.', max_length=80, verbose_name='Meses de pico (opcional)')),
                ('pais', models.CharField(blank=True, max_length=60, verbose_name='País')),
                ('estado', models.CharField(blank=True, max_length=60, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='Cidade')),
                ('possui_equipe_ti_dados', models.CharField(blank=True, choices=[('NAO', 'Não'), ('UMA_PESSOA', 'Sim, 1 pessoa'), ('EQUIPE_DEDICADA', 'Sim, equipe dedicada')], max_length=16, verbose_name='Possui equipe de TI / dados?')),
                ('alfabetizacao_digital_equipe', models.CharField(blank=True, choices=[('BAIXA', 'Baixo – dificuldade com novas ferramentas'), ('MEDIA', 'Médio – utilizam o básico bem'), ('ALTA', 'Alto – aprendem rápido e buscam inovação')], max_length=12, verbose_name='Nível de alfabetização digital da equipe')),
                ('ferramentas_gestao', models.CharField(blank=True, choices=[('NENHUMA', 'Nenhuma'), ('PAPEL', 'Papel / controles manuais'), ('PLANILHAS', 'Planilhas (Excel / Google Sheets)'), ('SOFTWARE_GENERALISTA', 'Software generalista (ERP, financeiro etc.)'), ('SOFTWARE_SETOR', 'Software específico do setor'), ('LEGADO', 'Sistema próprio / legado')], max_length=24, verbose_name='Ferramentas de gestão utilizadas atualmente')),
                ('residencia_dados', models.CharField(blank=True, choices=[('NAO_ARMAZENAMOS', 'Não armazenamos dados'), ('PAPEL', 'Papel / caderno'), ('PLANILHAS', 'Planilhas (Excel / Google)'), ('BANCO_DADOS', 'Banco de dados estruturado'), ('DISPERSOS', 'Dispersos em várias ferramentas')], max_length=20, verbose_name='Onde os dados da empresa residem hoje?')),
                ('prioridade_estrategica_ano', models.CharField(blank=True, choices=[('CUSTOS', 'Reduzir custos operacionais'), ('VENDAS', 'Aumentar volume de vendas'), ('EXPERIENCIA_CLIENTE', 'Melhorar a experiência do cliente'), ('ORGANIZACAO', 'Organizar processos e gestão'), ('EFICIENCIA', 'Aumentar eficiência operacional')], max_length=24, verbose_name='Prioridade estratégica para este ano')),
                ('conformidade_lgpd', models.CharField(blank=True, choices=[('NAO_IMPLEMENTADO', 'Não implementado'), ('EM_PROCESSO', 'Em processo de adequação'), ('CONFORME', 'Totalmente conforme'), ('NAO_SEI', 'Não sei informar')], max_length=20, verbose_name='Nível de conformidade com LGPD')),
                ('preferencia_entrega_recomendacoes', models.CharField(blank=True, choices=[('DIRETO', 'Mais direto e objetivo'), ('DETALHADO', 'Mais detalhado e explicativo'), ('EXECUTIVO', 'Visão executiva (decisão)'), ('OPERACIONAL', 'Visão operacional (execução)')], max_length=16, verbose_name='Como prefere receber as recomendações?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('setor_outro', models.CharField(blank=True, max_length=100, verbose_name='Outro setor (especifique)')),
                ('cargo_outro', models.CharField(blank=True, max_length=100, verbose_name='Outro cargo (especifique)')),
                ('segmento_outro', models.CharField(blank=True, max_length=100, verbose_name='Outro segmento (especifique)')),
                ('sistemas_outros', models.CharField(blank=True, help_text="Preencha se marcou 'Outros' no questionário de sistemas.", max_length=160, verbose_name='Outros sistemas (especifique)')),
                ('tipo_volume_mensal', models.CharField(blank=True, max_length=60, verbose_name='Tipo de volume mensal (ex.: pedidos, atendimentos, propostas, NFs)')),
                ('faixa_volume_mensal', models.CharField(blank=True, help_text='Faixa numérica definida conforme o setor. Ex.: 0–100 / 101–500 / 501–2.000 / 2.000+', max_length=40, verbose_name='Faixa de volume mensal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil da Empresa',
                'verbose_name_plural': 'Perfis das Empresas',
                'db_table': 'perfil_empresa',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresaCanaisAquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_aquisicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_empresas', to='perfil.canalaquisicaocliente', verbose_name='Canal de aquisição')),
                ('perfil_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_aquisicao', to='perfil.perfilempresa', verbose_name='Perfil da empresa')),
            ],
            options={
                'verbose_name': 'Canal de aquisição do perfil',
                'verbose_name_plural': 'Canais de aquisição dos perfis',
                'db_table': 'perfil_empresa_canais_aquisicao',
                'unique_together': {('perfil_empresa', 'canal_aquisicao')},
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresaObjetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.PositiveSmallIntegerField(blank=True, help_text='Use se o usuário ordenar objetivos. 1 = mais importante.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Prioridade (opcional)')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_empresas', to='perfil.objetivoproximo12meses', verbose_name='Objetivo')),
                ('perfil_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_12_meses', to='perfil.perfilempresa', verbose_name='Perfil da empresa')),
            ],
            options={
                'verbose_name': 'Objetivo do perfil',
                'verbose_name_plural': 'Objetivos dos perfis',
                'db_table': 'perfil_empresa_objetivos',
                'ordering': ['prioridade', 'id'],
                'unique_together': {('perfil_empresa', 'objetivo')},
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresaRestricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_criticas', to='perfil.perfilempresa', verbose_name='Perfil da empresa')),
                ('restricao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_empresas', to='perfil.restricaocritica', verbose_name='Restrição')),
            ],
            options={
                'verbose_name': 'Restrição do perfil',
                'verbose_name_plural': 'Restrições dos perfis',
                'db_table': 'perfil_empresa_restricoes',
                'unique_together': {('perfil_empresa', 'restricao')},
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresaSistemasUtilizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas_utilizados', to='perfil.perfilempresa', verbose_name='Perfil da empresa')),
                ('sistema_utilizado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_empresas', to='perfil.sistemautilizado', verbose_name='Sistema utilizado')),
            ],
            options={
                'verbose_name': 'Sistema do perfil',
                'verbose_name_plural': 'Sistemas dos perfis',
                'db_table': 'perfil_empresa_sistemas_utilizados',
                'unique_together': {('perfil_empresa', 'sistema_utilizado')},
            },
        ),
    ]
