# Generated by Django 6.0.1 on 2026-02-09 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Evento')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Evento')),
                ('processado_em', models.DateTimeField(auto_now_add=True, verbose_name='Processado em')),
                ('dados_json', models.TextField(blank=True, verbose_name='Dados JSON')),
            ],
            options={
                'verbose_name': 'Evento Mercado Pago',
                'verbose_name_plural': 'Eventos Mercado Pago',
                'ordering': ['-processado_em'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('ouro', 'Ouro')], unique=True, verbose_name='Identificador')),
                ('nome_exibicao', models.CharField(max_length=100, verbose_name='Nome de Exibição')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_centavos', models.PositiveIntegerField(verbose_name='Valor em Centavos')),
                ('moeda', models.CharField(default='brl', max_length=3, verbose_name='Moeda')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['valor_centavos'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=200, verbose_name='ID da Preferência MP')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID do Pagamento MP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='pagamentos.oferta', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AcessoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('ouro', 'Ouro')], max_length=20, verbose_name='Nível de Acesso')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('revogado', 'Revogado')], default='ativo', max_length=20, verbose_name='Status')),
                ('concedido_em', models.DateTimeField(auto_now_add=True, verbose_name='Concedido em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('ultima_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_concedidos', to='pagamentos.compra', verbose_name='Última Compra')),
            ],
            options={
                'verbose_name': 'Acesso de Usuário',
                'verbose_name_plural': 'Acessos de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Celular/WhatsApp')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
