# Generated by Django 4.2.7 on 2026-02-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessousuario',
            name='leads_consumidos_mes',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads consumidos no mês'),
        ),
        migrations.AddField(
            model_name='acessousuario',
            name='leads_limite_mensal',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads por mês'),
        ),
        migrations.AddField(
            model_name='acessousuario',
            name='mes_referencia',
            field=models.CharField(blank=True, max_length=7, verbose_name='Mês referência (YYYY-MM)'),
        ),
        migrations.AddField(
            model_name='compra',
            name='mercadopago_preapproval_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID da Assinatura MP'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='leads_mensais',
            field=models.PositiveIntegerField(default=0, verbose_name='Leads por mês'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Periodicidade'),
        ),
        migrations.AlterField(
            model_name='acessousuario',
            name='nivel',
            field=models.CharField(max_length=30, verbose_name='Nível de Acesso'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador'),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('authorized', 'Autorizada'), ('pending', 'Pendente Pagamento'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('mercadopago_preapproval_id', models.CharField(blank=True, max_length=200, verbose_name='ID da Assinatura MP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='pagamentos.oferta', verbose_name='Oferta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='acessousuario',
            name='ultima_assinatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_concedidos', to='pagamentos.assinatura', verbose_name='Última Assinatura'),
        ),
    ]
