# Generated by Django 6.0.1 on 2026-02-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('nome_projeto', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('segmento', models.CharField(max_length=200, verbose_name='Segmento')),
                ('objetivo_principal', models.TextField(verbose_name='Objetivo Principal')),
                ('objetivos_secundarios', models.JSONField(default=list, verbose_name='Objetivos Secundários')),
                ('problema', models.TextField(verbose_name='Problema')),
                ('causa_raiz', models.TextField(verbose_name='Causa Raiz')),
                ('impacto_do_problema', models.TextField(verbose_name='Impacto do Problema')),
                ('publico_impactado', models.TextField(verbose_name='Público Impactado')),
                ('solucao', models.TextField(verbose_name='Solução')),
                ('beneficios', models.JSONField(default=list, verbose_name='Benefícios')),
                ('impacto_operacional', models.TextField(verbose_name='Impacto Operacional')),
                ('impacto_financeiro', models.TextField(verbose_name='Impacto Financeiro')),
                ('impacto_tempo', models.TextField(verbose_name='Impacto Tempo')),
                ('indicadores_chave', models.JSONField(default=list, verbose_name='Indicadores Chave')),
                ('fases_projeto', models.JSONField(default=list, verbose_name='Fases do Projeto')),
                ('entregaveis', models.JSONField(default=list, verbose_name='Entregáveis')),
                ('riscos', models.JSONField(default=list, verbose_name='Riscos')),
                ('mitigacao_riscos', models.JSONField(default=list, verbose_name='Mitigação de Riscos')),
                ('dados_necessarios', models.JSONField(default=list, verbose_name='Dados Necessários')),
                ('vantagem_competitiva', models.TextField(verbose_name='Vantagem Competitiva')),
                ('casos_uso_futuros', models.JSONField(default=list, verbose_name='Casos de Uso Futuros')),
                ('prazo_minimo', models.PositiveIntegerField(default=0, verbose_name='Prazo Mínimo (semanas)')),
                ('prazo_maximo', models.PositiveIntegerField(default=0, verbose_name='Prazo Máximo (semanas)')),
                ('prazo_estimado', models.PositiveIntegerField(default=0, verbose_name='Prazo Estimado (semanas)')),
                ('preco_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço Mínimo (R$)')),
                ('preco_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço Máximo (R$)')),
                ('preco_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço Estimado (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_recomendados', to='perfil.perfilempresa')),
            ],
            options={
                'verbose_name': 'Projeto Recomendado',
                'verbose_name_plural': 'Projetos Recomendados',
                'ordering': ['area', 'nome_projeto'],
            },
        ),
    ]
