# Generated by Django 4.2.7 on 2026-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='prazo_estimado',
            field=models.CharField(default='', max_length=100, verbose_name='Prazo Estimado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prazo_maximo',
            field=models.CharField(default='', max_length=100, verbose_name='Prazo Máximo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prazo_minimo',
            field=models.CharField(default='', max_length=100, verbose_name='Prazo Mínimo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='preco_estimado',
            field=models.CharField(default='', max_length=100, verbose_name='Preço Estimado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='preco_maximo',
            field=models.CharField(default='', max_length=100, verbose_name='Preço Máximo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='preco_minimo',
            field=models.CharField(default='', max_length=100, verbose_name='Preço Mínimo'),
        ),
    ]
