# web/perfil/constants.py

SETORES_SEGMENTOS = {
    "AGRO": [
        ("AGR_FAMILIAR", "Agricultura familiar"),
        ("AGR_PRECISAO", "Agricultura de precisão"),
        ("GRAOS", "Grãos (soja, milho, trigo etc.)"),
        ("CAFE", "Café"),
        ("CANA", "Cana-de-açúcar"),
        ("HORTIFRUTI", "Hortifrúti / Olericultura"),
        ("FRUTICULTURA", "Fruticultura"),
        ("PEC_CORTE", "Pecuária de corte"),
        ("PEC_LEITE", "Pecuária leiteira"),
        ("AVICULTURA", "Avicultura"),
        ("SUINOCULTURA", "Suinocultura"),
        ("PISCICULTURA", "Piscicultura / Aquicultura"),
        ("APICULTURA", "Apicultura"),
        ("INSUMOS", "Insumos agrícolas (sementes, fertilizantes, defensivos)"),
        ("MAQUINAS_AGRO", "Máquinas e implementos agrícolas"),
        ("COOPERATIVAS", "Cooperativas agrícolas"),
        ("ARMAZENAGEM", "Armazenagem e silos"),
        ("AGROINDUSTRIAS", "Agroindústrias"),
        ("SERV_TECNICOS", "Serviços técnicos rurais"),
        ("LOGISTICA_AGRO", "Logística agrícola"),
        ("AGR_REGENERATIVA", "Agricultura regenerativa"),
        ("AGR_ORGANICA", "Agricultura orgânica certificada"),
        ("BIOTECH_AGRO", "Seed tech / biotecnologia agrícola"),
        ("MONITORAMENTO_AGRO", "Agtechs de monitoramento rural"),
        ("CREDITO_RURAL", "Crédito rural e financiamento agrícola"),
        ("SEGURO_AGRO", "Seguro agrícola"),
        ("RASTREABILIDADE", "Certificação e rastreabilidade agro"),
        ("GESTAO_RURAL", "Gestão de propriedades rurais"),
        ("IRRIGACAO", "Irrigação e manejo hídrico"),
        ("AGR_VERTICAL", "Agricultura vertical / indoor"),
        ("GEO_RURAL", "Serviços de georreferenciamento rural"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ALIMENTOS": [
        ("IND_ALIMENTICIA", "Indústria alimentícia"),
        ("PROCESS_CARNES", "Processamento de carnes"),
        ("LATICINIOS", "Laticínios"),
        ("PANIFICACAO", "Panificação / Confeitarias"),
        ("BEBIDAS_N_ALC", "Bebidas não alcoólicas"),
        ("BEBIDAS_ALC", "Bebidas alcoólicas (cervejaria, vinícola, destilaria)"),
        ("CONGELADOS", "Alimentos congelados"),
        ("FOOD_SERVICE", "Alimentos prontos / food service"),
        ("INGREDIENTES", "Ingredientes alimentícios"),
        ("DISTRIB_ALIMENTOS", "Distribuição de alimentos"),
        ("ATACADO_ALIM", "Atacado de alimentos"),
        ("VAREJO_ALIM", "Varejo alimentar"),
        ("RESTAURANTES", "Restaurantes"),
        ("COZINHAS_IND", "Cozinhas industriais"),
        ("DARK_KITCHENS", "Dark kitchens"),
        ("FUNC_NUTRAC", "Alimentos funcionais / nutracêuticos"),
        ("PLANT_BASED", "Alimentos plant-based"),
        ("GLUTEN_LACTOSE_FREE", "Alimentos sem glúten / sem lactose"),
        ("WHITE_LABEL_ALIM", "Marcas white-label alimentícias"),
        ("FOODTECHS", "Foodtechs"),
        ("ASSINATURA_ALIM", "Clubes de assinatura de alimentos"),
        ("ENERGETICOS", "Bebidas energéticas / isotônicos"),
        ("AGUA_MINERAL", "Água mineral / bebidas premium"),
        ("DIETAS_ESPECIAIS", "Alimentos para dietas especiais"),
        ("CO_PACKING", "Co-packing alimentício"),
        ("OUTRO", "Outro (descreva)")
    ],
    "PET": [
        ("CLINICAS_VET", "Clínicas veterinárias"),
        ("HOSPITAIS_VET", "Hospitais veterinários"),
        ("PET_SHOPS", "Pet shops"),
        ("BANHO_TOSA", "Banho e tosa"),
        ("HOTEL_PET", "Hotel / creche para pets"),
        ("ALIMENTACAO_PET", "Alimentação pet"),
        ("PRODUTOS_PET", "Produtos e acessórios pet"),
        ("PLANOS_SAUDE_PET", "Planos de saúde animal"),
        ("ADESTRAMENTO", "Treinamento / adestramento"),
        ("CRIACAO_PET", "Criação de animais"),
        ("DISTRIB_PET", "Distribuidores pet"),
        ("PET_TECH", "Pet tech / plataformas digitais pet"),
        ("GENETICA_PET", "Genética animal"),
        ("NUTRICAO_PET", "Nutrição animal especializada"),
        ("PRODU_VET", "Produtos veterinários"),
        ("PET_SITTER", "Serviços de pet sitter / dog walker"),
        ("TRANSPORTE_PET", "Transporte especializado para pets"),
        ("FUNERARIO_PET", "Crematórios / serviços funerários pet"),
        ("SEGUROS_PET", "Seguros para pets"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ARQUITETURA": [
        ("ARQ_RESIDENCIAL", "Arquitetura residencial"),
        ("ARQ_COMERCIAL", "Arquitetura comercial"),
        ("ARQ_CORPORATIVA", "Arquitetura corporativa"),
        ("INT_RESIDENCIAL", "Design de interiores residencial"),
        ("INT_COMERCIAL", "Design de interiores comercial"),
        ("PAISAGISMO", "Paisagismo"),
        ("ILUMINACAO", "Projetos de iluminação"),
        ("PROJETOS_3D", "Projetos 3D / renderização"),
        ("ESC_ARQUITETURA", "Escritórios de arquitetura"),
        ("CONS_ARQUITETURA", "Consultoria arquitetônica"),
        ("ARQ_HOSPITALAR", "Arquitetura hospitalar"),
        ("ARQ_INDUSTRIAL", "Arquitetura industrial"),
        ("ARQ_SUSTENTAVEL", "Arquitetura sustentável"),
        ("DESIGN_BIOFILICO", "Design biofílico"),
        ("ARQ_MODULAR", "Arquitetura modular"),
        ("RETROFIT", "Retrofit e requalificação"),
        ("CONS_VIABILIDADE", "Consultoria de viabilidade imobiliária"),
        ("ARQ_FRANQUIAS", "Arquitetura corporativa para franquias"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ARTISTICO": [
        ("PROD_MUSICAL", "Produção musical"),
        ("EST_GRAVACAO", "Estúdios de gravação"),
        ("PROD_AUDIOVISUAL", "Produtoras audiovisuais"),
        ("PROD_CULTURAL", "Produtoras culturais"),
        ("ART_IND", "Artistas independentes"),
        ("GESTAO_CARREIRA", "Gestão de carreira artística"),
        ("EV_CULTURAIS", "Eventos culturais"),
        ("AG_TALENTOS", "Agências de talentos"),
        ("LICENC_CONTEUDO", "Licenciamento de conteúdo"),
        ("DISTRIB_MUSICAL", "Distribuição musical"),
        ("PROD_PODCASTS", "Produção de podcasts"),
        ("POS_PRODUCAO", "Estúdios de pós-produção"),
        ("LICENC_TRILHAS", "Licenciamento de trilhas sonoras"),
        ("CONTEUDO_STREAMING", "Conteúdo para streaming"),
        ("MOTION_DESIGN", "Motion design"),
        ("CONTEUDO_EDU_AV", "Produção de conteúdo educacional audiovisual"),
        ("DIREITOS_AUTORAIS", "Gestão de direitos autorais"),
        ("SOUND_BRANDING", "Sound branding"),
        ("OUTRO", "Outro (descreva)")
    ],
    "AUTOMOBILISTICO": [
        ("CONCESSIONARIAS", "Concessionárias"),
        ("REVENDAS", "Revendas de veículos"),
        ("OFICINAS_MEC", "Oficinas mecânicas"),
        ("AUTOPE_AS", "Autopeças"),
        ("CENTROS_AUTO", "Centros automotivos"),
        ("FUNILARIA", "Funilaria e pintura"),
        ("ESTETICA_AUTO", "Serviços de estética automotiva"),
        ("LOCADORAS", "Locadoras de veículos"),
        ("FROTAS_CORP", "Frotas corporativas"),
        ("INSPECAO", "Inspeção veicular"),
        ("MOB_ELETRICA", "Mobilidade elétrica (serviços)"),
        ("INFRA_RECARGA", "Infraestrutura de recarga"),
        ("LINHA_DIESEL", "Veículos pesados / linha diesel"),
        ("BLINDAGEM", "Blindagem veicular"),
        ("RASTREAMENTO", "Rastreamento e telemetria"),
        ("SEGUROS_AUTO", "Seguros automotivos (operações)"),
        ("LEILOES", "Leilões de veículos"),
        ("OUTRO", "Outro (descreva)")
    ],
    "COMBUSTIVEIS": [
        ("POSTOS", "Postos de combustíveis"),
        ("DISTRIB_COMB", "Distribuidoras de combustíveis"),
        ("TRANSP_COMB", "Transporte de combustíveis"),
        ("GERACAO_ENERGIA", "Geração de energia"),
        ("COMERC_ENERGIA", "Comercialização de energia"),
        ("EFIC_ENERGETICA", "Eficiência energética"),
        ("BIOCOMBUSTIVEIS", "Biocombustíveis"),
        ("OLEO_GAS", "Óleo e gás (serviços)"),
        ("CRED_CARBONO", "Comercialização de créditos de carbono"),
        ("ENER_DISTRIBUIDA", "Energia distribuída"),
        ("EFIC_IND", "Eficiência energética industrial"),
        ("ARMAZEM_ENERGIA", "Armazenamento de energia"),
        ("HIDROGENIO", "Hidrogênio verde"),
        ("EOLICA", "Energia eólica (serviços)"),
        ("OUTRO", "Outro (descreva)")
    ],
    "CONSTRUCAO": [
        ("CONSTRUTORAS", "Construtoras"),
        ("INCORPORADORAS", "Incorporadoras"),
        ("OBRAS_RES", "Obras residenciais"),
        ("OBRAS_COM", "Obras comerciais"),
        ("OBRAS_IND", "Obras industriais"),
        ("INFRA_URBANA", "Infraestrutura urbana"),
        ("REFORMAS", "Reformas"),
        ("EMPREITEIRAS", "Empreiteiras"),
        ("MATERIAIS_CONST", "Materiais de construção"),
        ("ENG_CIVIL_APL", "Engenharia civil aplicada"),
        ("CONST_MODULAR", "Construção modular"),
        ("CONST_SUSTENTAVEL", "Construção sustentável / green building"),
        ("GERENC_OBRAS", "Gerenciamento de obras"),
        ("BIM", "BIM / modelagem digital"),
        ("FACILITIES_OBRAS", "Facilities para obras"),
        ("REG_IMOBILIARIA", "Regularização imobiliária"),
        ("LOTEAMENTOS", "Loteamentos"),
        ("OBRAS_PUB", "Obras públicas"),
        ("OUTRO", "Outro (descreva)")
    ],
    "CONTABILIDADE": [
        ("ESC_CONTABEIS", "Escritórios contábeis"),
        ("CONT_DIGITAL", "Contabilidade digital"),
        ("CONT_PMES", "Contabilidade para PMEs"),
        ("BPO_FIN", "BPO financeiro"),
        ("CONS_FISCAL", "Consultoria fiscal"),
        ("CONS_TRIB", "Consultoria tributária"),
        ("FOLHA_PAG", "Folha de pagamento"),
        ("AUD_CONTABIL", "Auditoria contábil"),
        ("CONT_STARTUPS", "Contabilidade para startups"),
        ("CONT_ECOMMERCE", "Contabilidade para e-commerce"),
        ("CONT_INTERNACIONAL", "Contabilidade internacional"),
        ("PLAN_SOCIETARIO", "Planejamento societário"),
        ("VALUATION", "Valuation"),
        ("RECUP_CRED_TRIB", "Recuperação de créditos tributários"),
        ("COMP_FISCAL", "Compliance fiscal"),
        ("OUTRO", "Outro (descreva)")
    ],
    "BELEZA": [
        ("IND_COSMETICA", "Indústria cosmética"),
        ("SALAO_BELEZA", "Salões de beleza"),
        ("CLIN_ESTETICA", "Clínicas de estética"),
        ("DIST_COSMETICOS", "Distribuição de cosméticos"),
        ("PERFUMARIAS", "Perfumarias"),
        ("MARCAS_D2C", "Marcas próprias (D2C)"),
        ("PROD_NATURA_VEG", "Produtos naturais/vegano"),
        ("PROF_AUTONOMOS", "Profissionais autônomos"),
        ("DERMOCOSMETICOS", "Dermocosméticos"),
        ("COSMET_FARMAC", "Cosméticos farmacêuticos"),
        ("EQUIP_ESTETICOS", "Equipamentos estéticos"),
        ("HARMONIZACAO", "Clínicas de harmonização facial"),
        ("BEAUTY_TECH", "Beauty tech"),
        ("DISTRIB_PROFES", "Distribuidores para profissionais"),
        ("MARCAS_NICHO", "Marcas de nicho (luxo, natural, infantil)"),
        ("OUTRO", "Outro (descreva)")
    ],
    "DIVERSOS": [
        ("SERV_GERAIS", "Serviços gerais"),
        ("COM_LOCAL", "Comércio local"),
        ("ATV_MISTAS", "Atividades mistas"),
        ("NEG_FAMILIARES", "Negócios familiares"),
        ("REP_COMERCIAIS", "Representações comerciais"),
        ("PREST_AUTONOMOS", "Prestadores autônomos"),
        ("ASSOC_EMPRESAR", "Associações empresariais"),
        ("COOP_N_AGRO", "Cooperativas não agrícolas"),
        ("ONGS", "ONGs"),
        ("FUND_PRIVADAS", "Fundações privadas"),
        ("ECON_CRIATIVA", "Economia criativa"),
        ("IMP_SOCIAL", "Negócios de impacto social"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ECOMMERCE": [
        ("LOJA_PROPRIA", "Loja virtual própria"),
        ("MARKET_B2C", "Marketplaces B2C"),
        ("MARKET_B2B", "Marketplaces B2B"),
        ("DROPSHIPPING", "Dropshipping"),
        ("ECOMM_D2C", "E-commerce D2C"),
        ("FULFILLMENT", "Fulfillment"),
        ("OMNICHANNEL", "Operação omnichannel"),
        ("PLAT_VENDA", "Plataformas de venda"),
        ("CROSS_BORDER", "Cross-border e-commerce"),
        ("SOCIAL_COMMERCE", "Social commerce"),
        ("LIVE_COMMERCE", "Live commerce"),
        ("MARKET_VERTICAIS", "Marketplaces verticais"),
        ("SELLERS_PROF", "Sellers profissionais"),
        ("BPO_ECOMMERCE", "Operadores de e-commerce (BPO)"),
        ("OUTRO", "Outro (descreva)")
    ],
    "EDUCACAO": [
        ("ESC_PRIVADAS", "Escolas privadas"),
        ("ENS_SUPERIOR", "Faculdades / ensino superior"),
        ("CURSOS_LIVRES", "Cursos livres"),
        ("EDU_CORP", "Educação corporativa"),
        ("EDTECHS", "Edtechs"),
        ("TREIN_TECNICOS", "Treinamentos técnicos"),
        ("ENS_EAD", "Ensino EAD"),
        ("PROD_CONT_EDU", "Produção de conteúdo educacional"),
        ("ESC_TECNICAS", "Escolas técnicas"),
        ("EDU_INFANTIL", "Educação infantil"),
        ("EDU_ESPECIAL", "Educação especial"),
        ("PLAT_AVAL_EDU", "Plataformas de avaliação educacional"),
        ("CONT_EDU_CORP", "Conteúdo educacional corporativo"),
        ("CERT_PROF", "Certificações profissionais"),
        ("PREP_CONCURSOS", "Preparatórios para concursos"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ENERGIA_SOLAR": [
        ("INTEGRADORES", "Integradores solares"),
        ("INST_FOTOV", "Instalação fotovoltaica"),
        ("PROJ_SOLARES", "Projetos solares"),
        ("MANUT_SIST", "Manutenção de sistemas"),
        ("COMERC_EQUIP", "Comercialização de equipamentos"),
        ("SOLAR_RES", "Energia solar residencial"),
        ("SOLAR_COM", "Energia solar comercial"),
        ("SOLAR_IND", "Energia solar industrial"),
        ("MONIT_USINAS", "Monitoramento remoto de usinas"),
        ("O_M_SOLAR", "O&M solar (operação e manutenção)"),
        ("SOLAR_COMP", "Energia solar compartilhada"),
        ("GER_D_ASSIN", "Geração distribuída por assinatura"),
        ("COMERC_EXCED", "Comercialização de excedente energético"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ENGENHARIA": [
        ("ENG_CIVIL", "Engenharia civil"),
        ("ENG_ELETRICA", "Engenharia elétrica"),
        ("ENG_MECANICA", "Engenharia mecânica"),
        ("ENG_AMBIENTAL", "Engenharia ambiental"),
        ("ENG_PRODUCAO", "Engenharia de produção"),
        ("CONS_TECNICA", "Consultoria técnica"),
        ("INFRA_ESTRUTURA", "Obras de infraestrutura"),
        ("PROJ_IND", "Projetos industriais"),
        ("ENG_TRAFEGO", "Engenharia de tráfego"),
        ("ENG_SEGURANCA", "Engenharia de segurança do trabalho"),
        ("ENG_TELECOM", "Engenharia de telecom"),
        ("ENG_PORTUARIA", "Engenharia portuária"),
        ("ENG_FERROVIARIA", "Engenharia ferroviária"),
        ("GESTAO_ATIVOS", "Gestão de ativos"),
        ("COMISS_IND", "Comissionamento industrial"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ELETRO": [
        ("IND_ELETRONICA", "Indústria eletrônica"),
        ("MONT_EQUIP", "Montagem de equipamentos"),
        ("VAR_ELETRONICOS", "Varejo de eletrônicos"),
        ("ASS_TECNICA", "Assistência técnica"),
        ("DIST_EQUIP", "Distribuição de equipamentos"),
        ("AUT_RES", "Automação residencial"),
        ("EQUIP_IND", "Equipamentos industriais"),
        ("IOT_RES", "IoT residencial"),
        ("IOT_IND", "IoT industrial"),
        ("WEARABLES", "Wearables"),
        ("AUT_COMERCIAL", "Equipamentos de automação comercial"),
        ("HARDWARE_SOB_MED", "Hardware sob medida"),
        ("ELETRO_EMBARCADOS", "Eletrônicos embarcados"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ESPORTE": [
        ("ACADEMIAS", "Academias"),
        ("EST_TREINO", "Estúdios de treino"),
        ("CLUBES_ESP", "Clubes esportivos"),
        ("ESC_ESP", "Escolas esportivas"),
        ("JOGOS_ESPORTS", "Jogos e e-sports"),
        ("WELLNESS", "Wellness / bem-estar"),
        ("PROD_ESP", "Produtos esportivos"),
        ("EVENTOS_ESP", "Eventos esportivos"),
        ("HEALTH_TECH", "Health tech"),
        ("TREINO_ONLINE", "Plataformas de treino online"),
        ("REAB_ESPORTIVA", "Clínicas de reabilitação esportiva"),
        ("TURISMO_ESP", "Turismo esportivo"),
        ("JOGOS_EDU", "Jogos educacionais"),
        ("GAMIFICACAO", "Gamificação corporativa"),
        ("OUTRO", "Outro (descreva)")
    ],
    "EVENTOS": [
        ("ORG_EVENTOS", "Organização de eventos"),
        ("EV_CORP", "Eventos corporativos"),
        ("EV_SOCIAIS", "Eventos sociais"),
        ("FEIRAS_EXPO", "Feiras e exposições"),
        ("PROD_TECNICA", "Produção técnica"),
        ("LOC_EQUIP", "Locação de equipamentos"),
        ("BUFFETS", "Buffets"),
        ("CENOGRAFIA", "Cenografia"),
        ("EV_HIBRIDOS", "Eventos híbridos"),
        ("PLAT_GESTAO_EV", "Plataformas de gestão de eventos"),
        ("TEC_EVENTOS", "Tecnologia para eventos"),
        ("EV_ESP", "Eventos esportivos"),
        ("EV_GOV", "Eventos governamentais"),
        ("EV_EDU", "Eventos educacionais"),
        ("OUTRO", "Outro (descreva)")
    ],
    "FARMACEUTICA": [
        ("IND_FARMAC", "Indústria farmacêutica"),
        ("DROGARIAS", "Drogarias"),
        ("FARM_MANIP_ACAO", "Farmácias de manipulação"),
        ("DISTRIB_FARMAC", "Distribuição farmacêutica"),
        ("PESQ_CLINICA", "Pesquisa clínica"),
        ("PROD_HOSPITALARES", "Produtos hospitalares"),
        ("COSMECEUTICOS", "Cosmecêuticos"),
        ("FARMACOVIGILANCIA", "Farmacovigilância"),
        ("LOGISTICA_FARMAC", "Logística farmacêutica"),
        ("CRO", "Pesquisa clínica terceirizada (CRO)"),
        ("M_GENERICOS", "Medicamentos genéricos"),
        ("M_BIOLOGICOS", "Medicamentos biológicos"),
        ("DISTRIB_HOSP_FARM", "Distribuição hospitalar farmacêutica"),
        ("OUTRO", "Outro (descreva)")
    ],
    "GESTAO": [
        ("CONS_EMPRESARIAL", "Consultoria empresarial"),
        ("CONS_ESTRATEGICA", "Consultoria estratégica"),
        ("GESTAO_PROC", "Gestão de processos"),
        ("GESTAO_FIN", "Gestão de financeira"),
        ("GESTAO_PROJ", "Gestão de projetos"),
        ("COACHING_CORP", "Coaching empresarial"),
        ("MENTORIA_EXEC", "Mentoria executiva"),
        ("CONS_DADOS_ANALYTICS", "Consultoria em dados e analytics"),
        ("CONS_IA", "Consultoria em IA"),
        ("CONS_ESG", "Consultoria em ESG"),
        ("CONS_M_A", "Consultoria em M&A"),
        ("CONS_TRANSF_DIGITAL", "Consultoria em transformação digital"),
        ("PMO_AAS", "PMO as a Service"),
        ("OUTRO", "Outro (descreva)")
    ],
    "IMOBILIARIA": [
        ("IMOB_RESIDENCIAIS", "Imobiliárias residenciais"),
        ("IMOB_COMERCIAIS", "Imobiliárias comerciais"),
        ("ADM_IMOVEIS", "Administração de imóveis"),
        ("LOCACAO_IMOB", "Locação"),
        ("COMPRA_VENDA", "Compra e venda"),
        ("AVAL_IMOB", "Avaliação imobiliária"),
        ("LANC_IMOB", "Lançamentos imobiliários"),
        ("PLAT_IMOB", "Plataformas imobiliárias"),
        ("IMOB_DIGITAIS", "Imobiliárias digitais"),
        ("GESTAO_CONDOMINIAL", "Gestão condominial"),
        ("PROPERTY_MGMT", "Property management"),
        ("LOC_TEMP_MGMT", "Locação por temporada (gestão)"),
        ("AVAL_PERICIA", "Avaliação e perícia imobiliária"),
        ("OUTRO", "Outro (descreva)")
    ],
    "IMPORT_EXPORT": [
        ("TRADING_COMPANIES", "Trading companies"),
        ("IMPORTADORES", "Importadores"),
        ("EXPORTADORES", "Exportadores"),
        ("DESP_ADUANEIRO", "Despacho aduaneiro"),
        ("LOG_INTERNACIONAL", "Logística internacional"),
        ("COM_EXTERIOR", "Comércio exterior"),
        ("IMP_TECNOLOGIA", "Importação de tecnologia"),
        ("EXP_AGRO_ESP", "Exportação agrícola especializada"),
        ("OP_TRIANGULARES", "Operações triangulares"),
        ("COMP_ADUANEIRO", "Compliance aduaneiro"),
        ("GESTAO_CAMBIAL", "Gestão cambial"),
        ("INT_COMEX", "Inteligência de comércio exterior"),
        ("OUTRO", "Outro (descreva)")
    ],
    "INVESTIMENTO": [
        ("ESC_INVESTIMENTO", "Escritórios de investimento"),
        ("PLAN_FINANCEIRO", "Planejamento financeiro"),
        ("CONS_FIN", "Consultoria financeira"),
        ("FINTECHS", "Fintechs"),
        ("CRED_FINANC", "Crédito e financiamento"),
        ("MEIOS_PAGTO", "Meios de pagamento"),
        ("AN_RISCO", "Análise de risco"),
        ("FAMILY_OFFICES", "Family offices"),
        ("GESTORAS_FUNDOS", "Gestoras de fundos"),
        ("WEALTH_MGMT", "Wealth management"),
        ("CRED_ESTRUTURADO", "Crédito estruturado"),
        ("AN_INVEST", "Análise de investimentos"),
        ("OPEN_FINANCE", "Open finance"),
        ("OUTRO", "Outro (descreva)")
    ],
    "JURIDICO": [
        ("ESC_ADVOCACIA", "Escritórios de advocacia"),
        ("ADV_EMPRESARIAL", "Advocacia empresarial"),
        ("ADV_TRABALHISTA", "Advocacia trabalhista"),
        ("ADV_TRIBUTARIA", "Advocacia tributária"),
        ("COMPLIANCE_JURID", "Compliance"),
        ("CONS_JURIDICA", "Consultoria jurídica"),
        ("MED_ARB", "Mediação e arbitragem"),
        ("LEGAL_OPS", "Legal operations"),
        ("LAWTECHS", "Lawtechs"),
        ("GESTAO_CONTRATOS", "Gestão de contratos"),
        ("PROT_DADOS_LGPD", "Proteção de dados / LGPD"),
        ("DIREITO_DIGITAL", "Direito digital"),
        ("DIREITO_REG", "Direito regulatório"),
        ("OUTRO", "Outro (descreva)")
    ],
    "LOGISTICA": [
        ("TRANSP_ROD", "Transporte rodoviário"),
        ("TRANSP_URBANO", "Transporte urbano"),
        ("DISTRIBUIDORAS", "Distribuidoras"),
        ("CENTROS_DIST", "Centros de distribuição"),
        ("ARMAZENAGEM_LOG", "Armazenagem"),
        ("LAST_MILE", "Logística last mile"),
        ("LOG_REVERSA", "Logística reversa"),
        ("FREIGHT_FORWARDERS", "Freight forwarders"),
        ("LOG_OMNICHANNEL", "Logística omnichannel"),
        ("TORRE_CONTROLE", "Torre de controle logística"),
        ("PLAN_MALHA", "Planejamento de malha logística"),
        ("LOG_INT_INTEGRADA", "Logística internacional integrada"),
        ("LOG_ECOMMERCE", "Logística de e-commerce"),
        ("LOG_FARMAC_ESP", "Logística farmacêutica especializada"),
        ("OUTRO", "Outro (descreva)")
    ],
    "MARKETING": [
        ("AG_MARKETING", "Agências de marketing"),
        ("MKT_DIGITAL", "Marketing digital"),
        ("TRAFEGO_PAGO", "Tráfego pago"),
        ("SEO_CONTEUDO", "SEO / conteúdo"),
        ("CRM_AUT_MKT", "CRM e automação"),
        ("BRANDING", "Branding"),
        ("GROWTH_MKT", "Growth marketing"),
        ("MARTECH", "Martech"),
        ("MKT_PERF_AV", "Marketing de performance avançado"),
        ("DATA_DRIVEN_MKT", "Data-driven marketing"),
        ("INT_MERCADO", "Inteligência de mercado"),
        ("CRO_MKT", "CRO (conversion rate optimization)"),
        ("MKT_B2B_TEC", "Marketing B2B técnico"),
        ("OUTRO", "Outro (descreva)")
    ],
    "MEDICINA_DIAG": [
        ("LAB_CLINICOS", "Laboratórios clínicos"),
        ("DIAG_IMAGEM", "Diagnóstico por imagem"),
        ("AN_LABORATORIAIS", "Análises laboratoriais"),
        ("LAB_ESPEC", "Laboratórios especializados"),
        ("COLETAS_DOM", "Coletas domiciliares"),
        ("PAT_DIGITAL", "Patologia digital"),
        ("GENOMICA", "Genômica"),
        ("BIO_MOLECULAR", "Biologia molecular"),
        ("LAB_REF", "Laboratórios de referência"),
        ("DIAG_VET", "Diagnóstico veterinário"),
        ("LAB_AMBIENTAIS", "Laboratórios ambientais"),
        ("OUTRO", "Outro (descreva)")
    ],
    "METALURGIA": [
        ("METALURGICAS", "Metalúrgicas"),
        ("SIDERURGICAS", "Siderúrgicas"),
        ("FUND_ICOES", "Fundições"),
        ("MINERACAO", "Mineração"),
        ("BENEF_MINERAL", "Beneficiamento mineral"),
        ("USINAGEM", "Usinagem"),
        ("CALDEIRARIA", "Caldeiraria"),
        ("METAL_PRECISAO", "Metalurgia de precisão"),
        ("BENEF_AVANCADO", "Beneficiamento avançado"),
        ("MIN_SUSTENTAVEL", "Mineração sustentável"),
        ("GEO_APLICADA", "Geologia aplicada"),
        ("MONIT_AMBIENTAL_MIN", "Monitoramento ambiental de minas"),
        ("OUTRO", "Outro (descreva)")
    ],
    "MAQUINAS": [
        ("FAB_MAQUINAS", "Fabricação de máquinas"),
        ("EQUIP_IND_TEC", "Equipamentos industriais"),
        ("MANUT_IND", "Manutenção industrial"),
        ("AUT_IND", "Automação industrial"),
        ("DIST_TECNICOS", "Distribuidores técnicos"),
        ("MANUFAT_ENCOMENDA", "Manufatura sob encomenda"),
        ("EQUIP_AGROIND", "Equipamentos para agroindústria"),
        ("EQUIP_MINERACAO", "Equipamentos para mineração"),
        ("RETROFIT_MAQUINAS", "Retrofit de máquinas"),
        ("MONIT_PREDITIVO", "Monitoramento preditivo"),
        ("OUTRO", "Outro (descreva)")
    ],
    "MEDICOS": [
        ("CLINICAS_MED", "Clínicas médicas"),
        ("CONSULTORIOS", "Consultórios"),
        ("CLIN_ODONT", "Clínicas odontológicas"),
        ("CENTROS_ESPEC", "Centros especializados"),
        ("INST_MEDICOS", "Institutos médicos"),
        ("TELEMEDICINA", "Telemedicina"),
        ("CLIN_IMAGEM", "Clínicas de imagem"),
        ("CLIN_ESPEC", "Clínicas de especialidades"),
        ("CENTROS_REAB", "Centros de reabilitação"),
        ("INST_PESQUISA_CLIN", "Institutos de pesquisa clínica"),
        ("CLIN_POPULARES", "Clínicas populares"),
        ("GESTAO_REDES_CLIN", "Gestão de redes clínicas"),
        ("OUTRO", "Outro (descreva)")
    ],
    "MOVEIS": [
        ("IND_MOVELEIRA", "Indústria moveleira"),
        ("MARCENARIAS", "Marcenarias"),
        ("LOJAS_MOVEIS", "Lojas de móveis"),
        ("DEC_RESIDENCIAL", "Decoração residencial"),
        ("DEC_CORPORATIVA", "Decoração corporativa"),
        ("PLANEJADOS", "Planejados"),
        ("DESIGN_AUTORAL", "Design autoral"),
        ("MOVEIS_CORP", "Móveis corporativos"),
        ("MOB_URBANO", "Mobiliário urbano"),
        ("DEC_SUSTENTAVEL", "Decoração sustentável"),
        ("ECOMM_DEC", "E-commerce de decoração"),
        ("FAB_SOB_MEDIDA", "Fabricação sob medida"),
        ("OUTRO", "Outro (descreva)")
    ],
    "PAPEL": [
        ("IND_PAPEL", "Indústria de papel"),
        ("CELULOSE", "Celulose"),
        ("EMBALAGENS", "Embalagens"),
        ("PLASTICOS_IND", "Plásticos industriais"),
        ("RECICLADOS_PLAS", "Reciclados plásticos"),
        ("EMB_FLEXIVEIS", "Embalagens flexíveis"),
        ("EMB_TECNICAS", "Embalagens técnicas"),
        ("PLAS_BIODEGRAD", "Plásticos biodegradáveis"),
        ("COMPOSITOS", "Compósitos"),
        ("TRANSF_PLASTICA", "Transformação plástica"),
        ("RECICLAGEM_QUIM", "Reciclagem química"),
        ("OUTRO", "Outro (descreva)")
    ],
    "HOSPITALAR": [
        ("EQUIP_MEDICOS", "Equipamentos médicos"),
        ("MAT_HOSPITALARES", "Materiais hospitalares"),
        ("DISTRIB_HOSP", "Distribuição hospitalar"),
        ("MANUT_EQUIP", "Manutenção de equipamentos"),
        ("TEC_MEDICA", "Tecnologia médica"),
        ("DISP_MEDICOS", "Dispositivos médicos"),
        ("EQUIP_DIAG", "Equipamentos de diagnóstico"),
        ("EQUIP_UTI", "Equipamentos de UTI"),
        ("TEC_HOSPITALAR", "Tecnologia hospitalar"),
        ("MANUT_HOSP_ESP", "Manutenção hospitalar especializada"),
        ("OUTRO", "Outro (descreva)")
    ],
    "PUBLICIDADE": [
        ("AG_PUB", "Agências de publicidade"),
        ("MIDIA_OFFLINE", "Mídia offline"),
        ("MIDIA_DIGITAL", "Mídia digital"),
        ("PROD_CRIATIVA", "Produção criativa"),
        ("PLAN_MIDIA", "Planejamento de mídia"),
        ("ADTECH", "Adtech"),
        ("MIDIA_PROG", "Planejamento de mídia programática"),
        ("CONT_PATROCINADO", "Conteúdo patrocinado"),
        ("MIDIA_OOH", "Mídia out-of-home (OOH)"),
        ("BRAND_EXP", "Brand experience"),
        ("OUTRO", "Outro (descreva)")
    ],
    "PUBLICO": [
        ("ORGAOS_PUB", "Órgãos públicos"),
        ("AUTARQUIAS", "Autarquias"),
        ("ESTATAIS", "Estatais"),
        ("PREFEITURAS", "Prefeituras"),
        ("SECRETARIAS", "Secretarias"),
        ("FUND_PUB", "Fundações públicas"),
        ("GOVTECH", "GovTech"),
        ("SMART_CITIES", "Cidades inteligentes"),
        ("PPP", "Parcerias público-privadas"),
        ("GESTAO_PUB", "Gestão de políticas públicas"),
        ("TRANSPARENCIA", "Transparência e dados abertos"),
        ("OUTRO", "Outro (descreva)")
    ],
    "QUIMICA": [
        ("IND_QUIMICA", "Indústria química"),
        ("QUIMICA_FINA", "Química fina"),
        ("PROD_IND_QUIM", "Produtos industriais"),
        ("INSUMOS_QUIMICOS", "Insumos químicos"),
        ("LAB_QUIMICOS", "Laboratórios químicos"),
        ("QUIMICA_VERDE", "Química verde"),
        ("QUIM_IND_PESADA", "Química industrial pesada"),
        ("ESPEC_QUIMICAS", "Especialidades químicas"),
        ("QUIM_ALIMENTOS", "Química para alimentos"),
        ("QUIM_COSMETICOS", "Química para cosméticos"),
        ("OUTRO", "Outro (descreva)")
    ],
    "RECICLAGEM": [
        ("COLETA_SELETIVA", "Coleta seletiva"),
        ("RECIC_IND", "Reciclagem industrial"),
        ("GESTAO_RESIDUOS", "Gestão de resíduos"),
        ("ECON_CIRCULAR", "Economia circular"),
        ("SUSTENTABILIDADE", "Sustentabilidade corporativa"),
        ("CRED_RECICLAGEM", "Créditos de reciclagem"),
        ("ESG_REPORTS", "ESG e relatórios de sustentabilidade"),
        ("MONIT_AMBIENTAL", "Monitoramento ambiental"),
        ("RESIDUOS_PERIGOSOS", "Gestão de resíduos perigosos"),
        ("ECON_CIRC_CORP", "Economia circular corporativa"),
        ("OUTRO", "Outro (descreva)")
    ],
    "ATACADO_VAREJO": [
        ("AT_ALIMENTAR", "Atacado alimentar"),
        ("AT_N_ALIMENTAR", "Atacado não alimentar"),
        ("VAR_FISICO", "Varejo físico"),
        ("VAR_ONLINE", "Varejo online"),
        ("REDES_FRANQ", "Redes franqueadas"),
        ("OMNICHANNEL_VAR", "Omnichannel"),
        ("FRANQUEADORAS", "Franqueadoras"),
        ("GESTAO_FRANQUIA", "Gestão de franquias"),
        ("NICHO_VAR", "Varejo de nicho"),
        ("CONVENIENCIA", "Varejo de conveniência"),
        ("AT_REGIONAL_ESP", "Atacado regional especializado"),
        ("OUTRO", "Outro (descreva)")
    ],
    "TELECOM": [
        ("PROVEDORES", "Provedores de internet"),
        ("TELECOM", "Telecom"),
        ("INFRA_REDE", "Infraestrutura de rede"),
        ("DATA_CENTERS", "Data centers"),
        ("CONECTIVIDADE", "Serviços de conectividade"),
        ("MVNO", "Operadores MVNO"),
        ("SEG_REDES", "Segurança de redes"),
        ("REDES_CORP", "Redes corporativas"),
        ("MONIT_INFRA", "Monitoramento de infraestrutura"),
        ("MSP", "Serviços gerenciados (MSP)"),
        ("OUTRO", "Outro (descreva)")
    ],
    "RH": [
        ("RECRUT_SELE_CAO", "Recrutamento e seleção"),
        ("HEADHUNTERS", "Headhunters"),
        ("BPO_RH", "BPO de RH"),
        ("TREIN_DESENV", "Treinamento e desenvolvimento"),
        ("GESTAO_TALENTOS", "Gestão de talentos"),
        ("HR_TECH", "HR Tech"),
        ("PEOPLE_ANALYTICS", "People analytics"),
        ("GESTAO_DESEMP", "Gestão de desempenho"),
        ("AVAL_COMPORT", "Avaliação comportamental"),
        ("EMPLOYER_BRANDING", "Employer branding"),
        ("EDU_CORP_RH", "Educação corporativa em RH"),
        ("OUTRO", "Outro (descreva)")
    ],
    "TI": [
        ("SA_SO_DEMANDA", "Software sob demanda"),
        ("SAAS_B2B", "SaaS B2B"),
        ("SAAS_B2C", "SaaS B2C"),
        ("SOFTWAREHOUSE", "Softwarehouse"),
        ("PLAT_DIGITAIS", "Plataformas digitais"),
        ("DEVOPS", "Cloud / DevOps"),
        ("SEG_INF", "Segurança da informação"),
        ("DADOS_IA", "Dados e IA"),
        ("LOW_NO_CODE", "Plataformas low-code / no-code"),
        ("DATA_PLATFORMS", "Data platforms"),
        ("IA_AAS", "IA como serviço"),
        ("CYBERSECURITY", "Cybersecurity"),
        ("OBSERVABILIDADE", "Observabilidade"),
        ("IPAAS", "Plataformas de integração (iPaaS)"),
        ("OUTRO", "Outro (descreva)")
    ],
    "SEGUROS": [
        ("CORRETORAS_SEG", "Corretoras de seguros"),
        ("SEGURADORAS", "Seguradoras"),
        ("BEN_CORP", "Benefícios corporativos"),
        ("GESTAO_APOLICES", "Gestão de apólices"),
        ("INSURTECHS", "Insurtechs"),
        ("SEG_CORP", "Seguros corporativos"),
        ("RESSEGUROS", "Resseguros"),
        ("SINISTROS", "Gestão de sinistros"),
        ("ATUARIAL", "Análise atuarial"),
        ("COT_SEG", "Plataformas de cotação"),
        ("OUTRO", "Outro (descreva)")
    ],
    "SEGURANCA_LIMPEZA": [
        ("SEG_PATRIMONIAL", "Segurança patrimonial"),
        ("MONITOR_MONIT", "Monitoramento"),
        ("PORTARIA", "Portaria"),
        ("LIMPEZA_PROF", "Limpeza profissional"),
        ("FACILITIES_LIMPEZA", "Facilities"),
        ("SEG_ELETRONICA", "Segurança eletrônica"),
        ("MONIT_INTELIGENTE", "Monitoramento inteligente"),
        ("FAC_CORP", "Facilities corporativo"),
        ("LIMP_HOSP", "Limpeza hospitalar"),
        ("LIMP_IND_ESP", "Limpeza industrial especializada"),
        ("OUTRO", "Outro (descreva)")
    ],
    "TRANSPORTE": [
        ("TRANSP_URBANO_MOB", "Transporte urbano"),
        ("MOB_CORP", "Mobilidade corporativa"),
        ("FROTAS_MOB", "Frotas"),
        ("LOG_PASSAGEIROS", "Logística de passageiros"),
        ("APP_MOBILIDADE", "Aplicativos de mobilidade"),
        ("MOB_ELET_CORP", "Mobilidade elétrica corporativa"),
        ("FROTAS_INT", "Gestão de frotas inteligentes"),
        ("TRANSP_DEMANDA", "Transporte sob demanda"),
        ("TRANSP_ESCOLAR", "Transporte escolar"),
        ("MOB_URB_INT", "Mobilidade urbana integrada"),
        ("OUTRO", "Outro (descreva)")
    ],
    "TURISMO": [
        ("HOTEIS", "Hotéis"),
        ("POUSADAS", "Pousadas"),
        ("RESORTS", "Resorts"),
        ("AG_TURISMO", "Agências de turismo"),
        ("OP_TURISMO", "Operadoras de turismo"),
        ("TURISMO_CORP", "Turismo corporativo"),
        ("ALUG_TEMP", "Aluguel por temporada"),
        ("REVENUE_MGMT", "Revenue management"),
        ("PLAT_RESERVAS", "Plataformas de reservas"),
        ("TUR_EXPERIENCIA", "Turismo de experiência"),
        ("TUR_SAUDE", "Turismo de saúde"),
        ("TUR_SUSTENTAVEL", "Turismo sustentável"),
        ("GESTAO_HOTEL_TERC", "Gestão hoteleira terceirizada"),
        ("OUTRO", "Outro (descreva)")
    ],
    "MODA": [
        ("IND_TEXTIL", "Indústria têxtil"),
        ("CONFECC_AO", "Confecção"),
        ("MARCAS_MODA", "Marcas de moda"),
        ("AT_VESTUARIO", "Atacado de vestuário"),
        ("VAR_MODA", "Varejo de moda"),
        ("MODA_D2C", "Moda D2C"),
        ("FAST_FASHION", "Fast fashion"),
        ("MODA_SUSTENTAVEL", "Moda sustentável"),
        ("MODA_INFANTIL", "Moda infantil"),
        ("MODA_ESPORTIVA", "Moda esportiva"),
        ("PRIVATE_LABEL", "Private label"),
        ("MODA_DIGITAL", "Plataformas de moda digital"),
        ("OUTRO", "Outro (descreva)")
    ],
    "COMUNICACAO": [
        ("JORNAIS", "Jornais"),
        ("REVISTAS", "Revistas"),
        ("RADIO", "Rádio"),
        ("TV", "TV"),
        ("PORTAIS_DIGITAIS", "Portais digitais"),
        ("PROD_CONTEUDO", "Produtoras de conteúdo"),
        ("PLAT_MIDIA_DIG", "Plataformas de mídia digital"),
        ("AGREG_CONTEUDO", "Agregadores de conteúdo"),
        ("MIDIA_REGIONAL", "Mídia regional"),
        ("CONT_ASSINATURA", "Conteúdo por assinatura"),
        ("JOR_DADOS", "Jornalismo de dados"),
        ("OUTRO", "Outro (descreva)")
    ],
    "OUTRO": [
        ("OUTRO", "Outro (descreva)")
    ]
}

# Default para setores não mapeados detalhadamente acima
DEFAULT_SEGMENTS = [
    ("SERVICOS", "Prestação de Serviços"),
    ("COMERCIO", "Comércio Varejista"),
    ("INDUSTRIA", "Indústria"),
    ("OUTRO", "Outro (descreva)")
]
