# Generated by Django 4.2.7 on 2026-02-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0002_alter_projeto_prazo_estimado_and_more'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_interesse', models.CharField(choices=[('ALTO', 'Alto Interesse - Prioridade'), ('MEDIO', 'Médio Interesse - Roadmap'), ('BAIXO', 'Baixo Interesse - Backlog'), ('DESCARTADO', 'Não tenho interesse'), ('JAEXISTE', 'Já possuo implementado')], max_length=20, verbose_name='Nível de Interesse')),
                ('feedback_texto', models.TextField(blank=True, null=True, verbose_name='Feedback/Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfilempresa')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Avaliação de Projeto',
                'verbose_name_plural': 'Avaliações de Projetos',
                'unique_together': {('projeto', 'perfil')},
            },
        ),
    ]
