# Generated by Django 6.0.1 on 2026-02-05 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilarQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilar', models.CharField(choices=[('TECNOLOGIA_SOFTWARE', 'Tecnologia e Software'), ('DADOS', 'Dados'), ('ANALYTICS', 'Analytics'), ('AUTOMACOES', 'Automações'), ('INTELIGENCIA_ARTIFICIAL', 'Inteligência Artificial')], max_length=40, unique=True, verbose_name='Pilar')),
                ('descricao', models.CharField(blank=True, max_length=180, verbose_name='Descrição')),
                ('ordem', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Pilar do Questionário',
                'verbose_name_plural': 'Pilares dos Questionários',
                'db_table': 'pilar_questionario',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoMaturidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Avaliação de Maturidade', max_length=120, verbose_name='Título')),
                ('pontuacao_geral', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pontuação geral (0-100)')),
                ('estagio_geral', models.CharField(choices=[('INICIAL', 'Inicial'), ('EM_EVOLUCAO', 'Em evolução'), ('ESTRUTURADO', 'Estruturado'), ('AVANCADO', 'Avançado')], default='INICIAL', max_length=20, verbose_name='Estágio geral')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('perfil_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_maturidade', to='perfil.perfilempresa', verbose_name='Perfil da empresa')),
            ],
            options={
                'verbose_name': 'Avaliação de Maturidade',
                'verbose_name_plural': 'Avaliações de Maturidade',
                'db_table': 'avaliacao_maturidade',
            },
        ),
        migrations.CreateModel(
            name='PerguntaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex.: DADOS_01, IA_07. Útil para versionamento e rastreio.', max_length=40, unique=True, verbose_name='Código')),
                ('ordem', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ordem')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('tipo_resposta', models.CharField(choices=[('MULTIPLA_ESCOLHA_A_E', 'Múltipla escolha (A-E)')], default='MULTIPLA_ESCOLHA_A_E', max_length=32, verbose_name='Tipo de resposta')),
                ('alternativa_a', models.CharField(max_length=240, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(max_length=240, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(max_length=240, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(max_length=240, verbose_name='Alternativa D')),
                ('alternativa_e', models.CharField(max_length=240, verbose_name='Alternativa E')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='questionarios.pilarquestionario', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Pergunta do Questionário',
                'verbose_name_plural': 'Perguntas do Questionário',
                'db_table': 'pergunta_questionario',
                'ordering': ['pilar__ordem', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_pilar', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pontuação do pilar (0-100)')),
                ('estagio_pilar', models.CharField(choices=[('INICIAL', 'Inicial'), ('EM_EVOLUCAO', 'Em evolução'), ('ESTRUTURADO', 'Estruturado'), ('AVANCADO', 'Avançado')], default='INICIAL', max_length=20, verbose_name='Estágio do pilar')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_pilares', to='questionarios.avaliacaomaturidade', verbose_name='Avaliação')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='questionarios.pilarquestionario', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Resposta do Pilar',
                'verbose_name_plural': 'Respostas dos Pilares',
                'db_table': 'resposta_questionario',
                'ordering': ['pilar__ordem'],
                'unique_together': {('avaliacao', 'pilar')},
            },
        ),
        migrations.CreateModel(
            name='RespostaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_escolhida', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e')], max_length=1, verbose_name='Alternativa escolhida')),
                ('pontuacao', models.PositiveSmallIntegerField(default=0, help_text='Sugestão: a=0, b=25, c=50, d=75, e=100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pontuação')),
                ('respondido_em', models.DateTimeField(auto_now_add=True, verbose_name='Respondido em')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='questionarios.perguntaquestionario', verbose_name='Pergunta')),
                ('resposta_questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_perguntas', to='questionarios.respostaquestionario', verbose_name='Resposta do pilar')),
            ],
            options={
                'verbose_name': 'Resposta da Pergunta',
                'verbose_name_plural': 'Respostas das Perguntas',
                'db_table': 'resposta_pergunta',
                'ordering': ['pergunta__pilar__ordem', 'pergunta__ordem'],
                'unique_together': {('resposta_questionario', 'pergunta')},
            },
        ),
    ]
