# Generated by Django 6.0.1 on 2026-02-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo_json', models.JSONField(verbose_name='Conteúdo do Relatório JSON')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_gerado', to='questionarios.avaliacaomaturidade')),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Relatórios Gerados',
                'db_table': 'relatorio_gerado',
            },
        ),
    ]
