# Generated by Django 4.2.7 on 2026-02-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Palavra-chave / Categoria')),
                ('cidade', models.CharField(max_length=150, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=150, verbose_name='Bairro')),
                ('usar_raio', models.BooleanField(default=False, verbose_name='Usar raio de busca')),
                ('raio_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Raio em km (1-50)')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Coleta',
                'verbose_name_plural': 'Coletas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, verbose_name='ID do Google Places')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('site', models.URLField(blank=True, max_length=500, verbose_name='Site')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Nota Google')),
                ('total_avaliacoes', models.PositiveIntegerField(default=0, verbose_name='Total de avaliações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.coleta', verbose_name='Coleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario'], name='crm_lead_usuario_84eab3_idx'), models.Index(fields=['coleta'], name='crm_lead_coleta__877d19_idx')],
                'unique_together': {('coleta', 'place_id')},
            },
        ),
    ]
