# Generated by Django 6.0.1 on 2026-02-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(max_length=300)),
                ('referer', models.URLField(blank=True, null=True)),
                ('page_visited', models.CharField(max_length=200)),
                ('machine_key', models.UUIDField(blank=True, null=True, verbose_name='Chave da Máquina')),
                ('username', models.CharField(default='Visitante', max_length=150, verbose_name='Nome do Usuário')),
            ],
        ),
    ]
